#version: '3'
services:
  android-builder:
    volumes:
      - ./:/work
    build:
      context: .
      secrets:
        - qt_acct_email
        - qt_acct_pw
    image: knowikiapps/scale-conf-android-builder:latest
secrets:
  qt_acct_email:
    file: qt_acct_email.txt
  qt_acct_pw:
    file: qt_acct_pw.txt
volumes:
  work:
