name: backend_refresh

on:
  schedule:
    - cron: '1,31 * * * *'
  workflow_dispatch:
  pull_request:
    branches: master
    paths:
      - ".github/workflows/backend_refresh.yml"

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: install deps
        shell: bash
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt update
          sudo apt install -y --no-install-recommends wget
      - name: refresh schedule
        run: |
          for try in 0 1 2 3; do
            wget https://scale-app-backend-113205d83b1f.herokuapp.com/refresh && break
            echo "Refreshing schedule data failed, attempt $try, sleeping 5 seconds and retrying"
            sleep 5
          done
      - name: refresh speakers
        run: |
          for try in 0 1 2 3; do
            wget https://scale-app-backend-113205d83b1f.herokuapp.com/refresh/speakers && break
            echo "Refreshing speaker data failed, attempt $try, sleeping 5 seconds and retrying"
            sleep 5
          done
