name: backend_refresh

on:
  schedule:
    - cron: '1,31 * * * *'
  workflow_dispatch:
  pull_request:
    branches: master
    paths:
      - ".github/workflows/backend_refresh.yml"

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: install deps
        shell: bash
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt update
          sudo apt install -y --no-install-recommends wget
      - name: refresh events
        run: wget https://scale-app-backend-113205d83b1f.herokuapp.com/refresh
      - name: refresh speakers
        run: wget https://scale-app-backend-113205d83b1f.herokuapp.com/refresh/speakers
